apiVersion: v1
kind: Service
metadata:
  name: <app service>
  labels:
    job: <app job name>
    name: <app name>
spec:
  selector:
    app: <app name>
  ports:
    - name: web
      port: 8090
      targetPort: 8090
  type: LoadBalancer