apiVersion: apps/v1
kind: Deployment
metadata:
  name: <app_name>-deployment
  #namespace: tenant-1
  labels:
    app: <app_name>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <app_name>
  template:
    metadata:
      labels:
        app: <app_name>
    spec:
      containers:
      - name: <app_name>
        image: (change to your docker image ex asas00/appname:latest)
        ports:
        - containerPort: 6009
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100"
