apiVersion: v1
kind: Service
metadata:
  name: <app_name>-service
  labels:
    job: s0-api
    name: <app_name>
spec:
  selector:
    app: <app_name>
  ports:
    - name: web
      port: 6009
      targetPort: 6009
  type: LoadBalancer